features=['trip_distance', 'driver_distance', 'driver_gps_accuracy','event_hour','completed_booking_count']
target="is_completed"
test_size=0.2

[random_forest]
n_estimators=300
max_depth=30
n_jobs=-1
random_state=33
bootstrap=false
